name: 'dismiss-stale-reviews'
on:
  pull_request:

jobs:
  dismiss-stale-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # the git history must be fetched until merge-base commit of pull-request
          fetch-depth: 0

      # in case you use team handles in your CODEOWNERS file, you need to get a GitHub App token with advanced permissions:
      repository contents: read
      repository pull requests: write
      organization members: read
      # for more info on how to use GitHub App token check https://github.com/actions/create-github-app-token
      - uses: actions/create-github-app-token@v1
        id: get-token
        with:
          private-key: ${{ secrets.MANAGE_REVIEWS_BOT_PEM }}
          app-id: ${{ vars.MANAGE_REVIEWS_BOT_ID }}

      - uses: balvajs/dismiss-stale-reviews@v3
        with:
          token: ${{ steps.get-token.outputs.token }}
